### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by liamdiprose** [mattwparas/steel#85]
Thanks for this project, its exciting to see a scheme in Rust, I think it they compliment each other well (with regards to development vs run time, experimental vs standardized).

Although I can see the value in keeping it the future open, I was wondering what your goals for this project were? 

Specifically, your thoughts on compatibly with:

- no_std
- async
- wasm
- non-lisp syntax extensions

**Comment by mattwparas** [comment]
Thanks for the kind words. To address each one:

* no_std - This is something that was never an explicit goal. I think it would be a pretty big lift to make steel no_std compatible, and it is certainly something I would _like_ to do, but lower on the list
* async - Steel is able to call async functions currently, and can drive the results to completion. With some funny business with continuations, you can emulate an async runtime and integrate with something like tokio. Its slightly non trivial, but I think eventually this will be more clear. I don't particularly have any goals with making the entire runtime async on its own, i.e. require an external runtime to run.
* wasm - a few years ago I was able to compile the core to wasm, so this is very much a goal. I think the only thing I needed to abstract away was file system work, otherwise everything seemed to compile to wasm just fine (that is how the existing playground works, although the build it is using is a few years old now)
* non-lisp syntax extensions - could you elaborate on this a bit? Not sure what you have in mind. As of now the intent is for macros to be used to extend the syntax. Are you referring to an alternative syntax entirely?

**Comment by liamdiprose** [comment]
Great to hear async is already supported!

I assumed wasm was a no_std environment; there are no_std wasm runtimes. I might investigate this further, since I'm in the embedded world at the moment. I'll be in touch if anything comes of it.

> non-lisp syntax extensions - could you elaborate on this a bit?

[`#lang datalog`](https://github.com/racket/datalog/blob/master/tests/examples/ancestor.rkt) for example. Now that I've thought about it a bit more, maybe it would be better to have other parts of the Rust ecosystem handle parsing and use Rust (or Steel) to transform the AST into scheme before it is passed into the Steel VM.

**Comment by mattwparas** [comment]
I see, yeah, Racket's macro system is exceptionally powerful and while I would say an extremely lofty long term goal would be to replicate that, it is not explicitly a short term goal for the project.

That being said, for the latter point about manipulating the AST, yeah. I did try to make the majority of the internals act as a library - you can add passes to the compilation process pretty easily, so with some work the underlying compiler and VM could be used by another library to compile to scheme.

**Comment by mattwparas** [comment]
And again with respect to no_std - it would probably be quite a bit of work, but definitely something I'm interested in pursuing if there is interest and perhaps commitment on help with the implementation

**Comment by liamdiprose** [comment]
I've just found out the embedded device I'm using (esp32) supports std anyway. I have no idea how.

I really appreciate the offer to help. If I make any substantial progress I'll open a PR :+1:

**Comment by mattwparas** [comment]
If you do happen to run into any issues running on the device, feel free to open another issue, happy to help!
